const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '../public_html');
const out = path.resolve(__dirname, '../../tmp/checkout-qa');
fs.mkdirSync(out, { recursive: true });
const render = (mode = '') => execFileSync('php', [path.join(__dirname, 'checkout-render.php'), mode], { encoding: 'utf8' });
const pages = Object.fromEntries(['', 'disabled', 'prefilled'].map((mode) => [mode, render(mode)]));
const mime = { '.css': 'text/css', '.js': 'text/javascript', '.png': 'image/png', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' };
const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://localhost');
  if (url.pathname === '/') { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(pages[url.searchParams.get('mode') || '']); return; }
  const file = path.resolve(root, '.' + decodeURIComponent(url.pathname));
  if (!file.startsWith(root + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404); res.end(); return; }
  res.setHeader('Content-Type', mime[path.extname(file)] || 'application/octet-stream'); fs.createReadStream(file).pipe(res);
});
let checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; };
(async () => {
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
  try {
    const context = await browser.newContext({ locale: 'en-US', viewport: { width: 1440, height: 1080 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('console', (message) => { if (message.type() === 'error' && !message.text().includes('status of 422')) errors.push(message.text()); });
    let failure = false;
    let delay = 0;
    let starts = 0;
    let bankSuccess = false;
    let bankPosts = 0;
    let quotes = 0;
    let payload;
    await page.route('**/api/auth/csrf', (route) => route.fulfill({ json: { csrfToken: 'ui-token' } }));
    await page.route('**/api/payments/quote', async (route) => {
      quotes++;
      const input = route.request().postDataJSON();
      check(!Object.keys(input).some((key) => /card|contact|address/i.test(key)), 'No personal/card data in quote');
      const days = Math.ceil((Date.parse(`${input.dropoffDate}T${input.dropoffTime}:00Z`) - Date.parse(`${input.pickupDate}T${input.pickupTime}:00Z`)) / 86400000);
      const wait = delay;
      if (wait) await new Promise((resolve) => setTimeout(resolve, wait));
      if (failure) return route.fulfill({ status: 422, json: { error: 'Seçilen tarihlerde araç müsait değil.' } });
      return route.fulfill({ json: { amount: String(85 * days * 40), dailyUsd: '85.00', days, currency: 'TRY', quoteToken: `ui-quote-${days}`, expiresAt: Math.floor(Date.now() / 1000) + 300 } });
    });
    await page.route('**/api/payments/start', async (route) => {
      starts++; payload = route.request().postDataJSON();
      await new Promise((resolve) => setTimeout(resolve, 100));
      if (bankSuccess) return route.fulfill({ json: { challenge: { action: 'https://inbound.apigatewaytest.vakifbank.com.tr/threeDGateway/startThreeDFlow', fields: { PaReq: 'ui-pareq', MD: 'ui-md' } } } });
      return route.fulfill({ status: 422, json: { error: 'Banka test yanıtı: işlem başlatılamadı.' } });
    });
    await page.route('https://inbound.apigatewaytest.vakifbank.com.tr/**', async (route) => {
      bankPosts++;
      check(route.request().method() === 'POST', 'Challenge uses POST');
      const body = new URLSearchParams(route.request().postData());
      check(body.get('PaReq') === 'ui-pareq' && body.get('MD') === 'ui-md' && [...body.keys()].length === 2, 'Only bank challenge fields sent');
      await route.fulfill({ contentType: 'text/html', body: '<title>Intercepted bank challenge</title>' });
    });
    await page.goto(base);
    check(await page.locator('[data-step="0"]').isVisible(), 'Rental is initial step');
    check(await page.locator('.pay-button').isHidden(), 'Payment not shown before dates');
    await page.locator('#step-next').click();
    check(await page.locator('#pickup-display').evaluate((el) => !el.checkValidity()), 'Empty date prevents progress');
    await page.locator('#pickup-display').fill('31.02.2027');
    await page.waitForTimeout(650);
    check(await page.locator('#pickup-error').textContent() !== '', 'Impossible date explained');
    const future = (days) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10).split('-').reverse().join('.');
    await page.locator('#pickup-display').fill(future(10));
    await page.locator('#dropoff-display').fill(future(12));
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '2 gün');
    check(await page.locator('#quote-total').textContent() === '₺6.800,00', 'Automatic daily x days x FX total');
    check(await page.locator('#price-breakdown').textContent() === '$85,00 × 2 gün = $170,00', 'Visible daily price breakdown');
    check(await page.locator('#quote-refresh').isHidden(), 'No manual refresh required');
    await page.screenshot({ path: path.join(out, 'desktop-rental.png'), fullPage: true });
    await page.locator('#dropoff-display').fill(future(13));
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '3 gün');
    check(await page.locator('#quote-total').textContent() === '₺10.200,00', 'Date change automatically recalculates');
    await page.locator('[name=dropoffTime]').fill('10:00');
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '4 gün');
    check(true, 'Partial extra rental day uses backend rounding');
    await page.locator('[name=dropoffTime]').fill('09:00');
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '3 gün');
    await page.locator('#step-next').click();
    check(await page.locator('[data-step="1"]').isVisible(), 'Valid rental advances');
    await page.locator('#step-next').click();
    check(await page.locator('[data-step="1"]').isVisible(), 'Missing personal details block advancement');
    for (const [name, value] of Object.entries({contactName: 'Test Customer', contactEmail: 'test@example.test', contactPhone: '+905550000000', city: 'Trabzon', zipCode: '61000', address: 'Test Street Number 10'})) await page.locator(`[name=${name}]`).fill(value);
    await page.locator('#step-next').click();
    check(await page.locator('[data-step="2"]').isVisible(), 'Details advance to payment');
    await page.locator('[name=cardNumber]').fill('4938410109068353');
    await page.locator('[name=expiryMonth]').fill('12');
    await page.locator('[name=expiryYear]').fill('2029');
    await page.locator('.pay-button').click();
    check(starts === 0, 'Missing consents prevent start');
    for (const input of await page.locator('.consent input').all()) await input.check();
    await page.screenshot({ path: path.join(out, 'desktop-payment.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Payment fits mobile');
    await page.screenshot({ path: path.join(out, 'mobile-payment.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1080 });
    await page.locator('.pay-button').click();
    await page.waitForFunction(() => document.querySelector('#payment-error').textContent.includes('Banka test')); 
    check(starts === 1, 'One submission produces one payment start');
    check(payload.pickupDate.match(/^\d{4}-\d{2}-\d{2}$/), 'Bank start retains ISO date contract');
    check(payload.termsAccepted === true && payload.privacyNoticeAccepted === true, 'Consent values are booleans');
    check(await page.locator('[name=cardNumber]').inputValue() === '', 'Card cleared after bank failure');
    check(await page.locator('.pay-button').isDisabled(), 'Failure invalidates quote');
    check(await page.locator('#quote-refresh').isVisible(), 'Failed request offers retry');
    await page.locator('[data-step-target="0"]').click();
    failure = true;
    await page.locator('#dropoff-display').fill(future(14));
    await page.waitForFunction(() => document.querySelector('#quote-feedback').textContent.includes('müsait değil'));
    check(await page.locator('#quote-refresh').isVisible(), 'Quote error offers retry');
    failure = false;
    await page.locator('#quote-refresh').click();
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '4 gün');
    check(true, 'Quote retry recovers');
    delay = 1000;
    await page.locator('#dropoff-display').fill(future(15));
    await page.waitForTimeout(550);
    delay = 0;
    await page.locator('#dropoff-display').fill(future(16));
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '6 gün');
    await page.waitForTimeout(700);
    check(await page.locator('#quote-days').textContent() === '6 gün', 'Late quote cannot overwrite latest dates');
    for (const width of [390, 320, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No horizontal overflow at ${width}`);
      check(await page.locator('img').evaluateAll((imgs) => imgs.every((img) => img.complete && img.naturalWidth > 0)), `Images loaded at ${width}`);
      if (width === 390) await page.screenshot({ path: path.join(out, 'mobile-rental.png'), fullPage: true });
    }
    await page.goto(base + '/?mode=prefilled');
    await page.waitForFunction(() => document.querySelector('#quote-days').textContent === '3 gün');
    check(await page.locator('#pickup-display').inputValue() === future(10), 'Prefilled dates display DD.MM.YYYY even in English browser');
    await page.locator('#step-next').click();
    for (const [name, value] of Object.entries({contactName: 'Test Customer', contactEmail: 'test@example.test', contactPhone: '+905550000000', city: 'Trabzon', zipCode: '61000', address: 'Test Street Number 10'})) await page.locator(`[name=${name}]`).fill(value);
    await page.locator('#step-next').click();
    await page.locator('[name=cardNumber]').fill('4938410109068353');
    await page.locator('[name=expiryMonth]').fill('12');
    await page.locator('[name=expiryYear]').fill('2029');
    for (const input of await page.locator('.consent input').all()) await input.check();
    bankSuccess = true;
    await page.locator('.pay-button').click();
    await page.waitForURL('https://inbound.apigatewaytest.vakifbank.com.tr/**');
    check(bankPosts === 1, 'Successful start redirects to intercepted 3D challenge, no bank network');
    const before = quotes;
    await page.goto(base + '/?mode=disabled');
    await page.waitForTimeout(600);
    check(quotes === before && await page.locator('#step-next').isDisabled(), 'Disabled provider never requests payment quote');
    check(await page.locator('#checkout-status').textContent() !== '', 'Disabled mode explains state');
    check(errors.length === 0, `Browser errors: ${errors.join(' | ')}`);
    console.log(JSON.stringify({ checks, result: 'PASS', screenshots: out }));
  } finally { await browser.close(); server.close(); }
})().catch((error) => { console.error(error); server.close(); process.exitCode = 1; });
