(() => {
  const requestForm=document.querySelector('#request-form'); const confirmForm=document.querySelector('#confirm-form'); const message=document.querySelector('#message'); let email='';
  async function csrf(){const response=await fetch('/api/auth/csrf',{credentials:'same-origin'});if(!response.ok)throw new Error('Güvenlik doğrulaması başlatılamadı.');return (await response.json()).csrfToken}
  function show(text,error=false){message.textContent=text;message.classList.toggle('error',error);message.hidden=false}
  async function send(url,payload){const token=await csrf();const response=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(payload)});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error||'İşlem tamamlanamadı.');return result}
  requestForm.addEventListener('submit',async(event)=>{event.preventDefault();const button=requestForm.querySelector('button');button.disabled=true;try{email=String(new FormData(requestForm).get('email')||'').trim().toLowerCase();const result=await send('/api/auth/password/request',{email});show(result.message);requestForm.hidden=true;confirmForm.hidden=false}catch(error){show(error.message,true)}finally{button.disabled=false}});
  confirmForm.addEventListener('submit',async(event)=>{event.preventDefault();const data=new FormData(confirmForm);const password=String(data.get('password')||'');if(password!==String(data.get('passwordConfirm')||''))return show('Yeni şifreler birbiriyle aynı olmalıdır.',true);const button=confirmForm.querySelector('button');button.disabled=true;try{await send('/api/auth/password/confirm',{email,code:String(data.get('code')||''),password});show('Şifreniz yenilendi. Giriş ekranına yönlendiriliyorsunuz.');setTimeout(()=>window.location.assign('/?account=overview'),1200)}catch(error){show(error.message,true);button.disabled=false}});
  document.querySelector('#restart').addEventListener('click',()=>{confirmForm.hidden=true;requestForm.hidden=false;message.hidden=true;confirmForm.reset()});
})();
